#!/usr/bin/env bash
# DevOpsSentinel Web -- install the optional client tools WITHOUT sudo.
#
# The Doctor page reports `psql`, `kafka-topics.sh`, `kafka-topics`,
# `kafka-consumer-groups.sh` and `kafka-consumer-groups` as NOT INSTALLED when
# they are missing. The engine uses them for its interactive PostgreSQL and
# Kafka checks, and the opt-in live-data features are easier to verify with
# them present.
#
# Everything lands in ~/.local (already on PATH on most distros):
#
#   ~/.local/pg      PostgreSQL client, extracted from the distro .deb files
#   ~/.local/jdk-21  Temurin JDK (the Kafka scripts are Java programs)
#   ~/.local/kafka   Apache Kafka CLI
#   ~/.local/bin     thin wrappers that wire the two together
#
# Usage:  scripts/install-cli-tools.sh [--psql-only|--kafka-only]
set -euo pipefail

LOCAL="${HOME}/.local"
BIN="${LOCAL}/bin"
PG_PREFIX="${LOCAL}/pg"
JDK_DIR="${LOCAL}/jdk-21"
KAFKA_DIR="${LOCAL}/kafka"
JDK_URL="https://api.adoptium.net/v3/binary/latest/21/ga/linux/x64/jdk/hotspot/normal/eclipse"
KAFKA_VERSION="3.9.1"
KAFKA_URL="https://archive.apache.org/dist/kafka/${KAFKA_VERSION}/kafka_2.13-${KAFKA_VERSION}.tgz"

WANT_PSQL=1
WANT_KAFKA=1
case "${1:-}" in
    --psql-only) WANT_KAFKA=0 ;;
    --kafka-only) WANT_PSQL=0 ;;
    "") ;;
    *) printf 'usage: %s [--psql-only|--kafka-only]\n' "$0" >&2; exit 2 ;;
esac

log() { printf '[install-cli-tools] %s\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || { printf '%s is required\n' "$1" >&2; exit 3; }; }

mkdir -p "$BIN"

# ------------------------------------------------------------------ psql
if [[ "$WANT_PSQL" == "1" ]] && ! command -v psql >/dev/null 2>&1; then
    need curl
    need apt-get
    need dpkg-deb
    log "installing the PostgreSQL client into $PG_PREFIX (no root needed)"
    tmp=$(mktemp -d)
    # `apt-get download` resolves versions from the local package lists and does
    # not require root; `dpkg -x` just unpacks the archive.
    ( cd "$tmp" && apt-get download postgresql-client-16 libpq5 >/dev/null 2>&1 ) || {
        printf 'apt-get download failed - are the package lists available?\n' >&2
        exit 4
    }
    for deb in "$tmp"/*.deb; do dpkg -x "$deb" "$PG_PREFIX"; done
    rm -rf "$tmp"

    PG_BIN="${PG_PREFIX}/usr/lib/postgresql/16/bin"
    PG_LIB="${PG_PREFIX}/usr/lib/x86_64-linux-gnu"
    for tool in psql pg_dump pg_dumpall pg_restore pg_isready createdb dropdb createuser dropuser vacuumdb reindexdb; do
        [[ -x "${PG_BIN}/${tool}" ]] || continue
        cat > "${BIN}/${tool}" <<WRAP
#!/usr/bin/env bash
# Generated by scripts/install-cli-tools.sh
export LD_LIBRARY_PATH="${PG_LIB}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
exec "${PG_BIN}/${tool}" "\$@"
WRAP
        chmod +x "${BIN}/${tool}"
    done
    log "psql -> $(command -v psql || echo "${BIN}/psql")"
else
    log "psql already present or skipped"
fi

# ------------------------------------------------------------------ kafka
if [[ "$WANT_KAFKA" == "1" ]]; then
    need curl
    need tar

    if [[ ! -x "${JDK_DIR}/bin/java" ]]; then
        log "downloading a JDK into $JDK_DIR"
        tmp=$(mktemp -d)
        curl -fL --retry 3 --retry-delay 2 -o "$tmp/jdk.tar.gz" "$JDK_URL"
        mkdir -p "$JDK_DIR"
        tar -xzf "$tmp/jdk.tar.gz" -C "$JDK_DIR" --strip-components=1
        rm -rf "$tmp"
    fi

    if [[ ! -x "${KAFKA_DIR}/bin/kafka-topics.sh" ]]; then
        log "downloading Kafka ${KAFKA_VERSION} into $KAFKA_DIR"
        tmp=$(mktemp -d)
        curl -fL --retry 3 --retry-delay 2 -o "$tmp/kafka.tgz" "$KAFKA_URL"
        mkdir -p "$KAFKA_DIR"
        tar -xzf "$tmp/kafka.tgz" -C "$KAFKA_DIR" --strip-components=1
        rm -rf "$tmp"
    fi

    # The engine probes for BOTH `kafka-topics.sh` and `kafka-topics`, and the
    # upstream tarball only ships the `.sh` names, so create both.
    for tool in kafka-topics kafka-consumer-groups kafka-console-producer \
                kafka-console-consumer kafka-configs kafka-get-offsets \
                kafka-broker-api-versions kafka-verifiable-producer; do
        [[ -f "${KAFKA_DIR}/bin/${tool}.sh" ]] || continue
        for name in "$tool" "${tool}.sh"; do
            cat > "${BIN}/${name}" <<WRAP
#!/usr/bin/env bash
# Generated by scripts/install-cli-tools.sh
export JAVA_HOME="${JDK_DIR}"
export PATH="\$JAVA_HOME/bin:\$PATH"
export KAFKA_HEAP_OPTS="\${KAFKA_HEAP_OPTS:--Xms256m -Xmx512m}"
exec "${KAFKA_DIR}/bin/${tool}.sh" "\$@"
WRAP
            chmod +x "${BIN}/${name}"
        done
    done

    cat > "${BIN}/java" <<WRAP
#!/usr/bin/env bash
# Generated by scripts/install-cli-tools.sh
export JAVA_HOME="${JDK_DIR}"
exec "\$JAVA_HOME/bin/java" "\$@"
WRAP
    chmod +x "${BIN}/java"

    log "java    -> $(command -v java || echo "${BIN}/java")"
    log "kafka   -> $(command -v kafka-topics.sh || echo "${BIN}/kafka-topics.sh")"
fi

# ------------------------------------------------------------------ report
log "tool status (what the Doctor page checks):"
for tool in psql kafka-topics.sh kafka-topics kafka-consumer-groups.sh kafka-consumer-groups; do
    printf '  %-28s %s\n' "$tool" "$(command -v "$tool" 2>/dev/null || echo MISSING)"
done
log "done - restart the backend so the engine picks the tools up"
